name: CI/CD Pipeline LKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Docker image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build Image dari Dockerfile
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          
          # Simpan URI Image ke Env Var biar bisa dipanggil langkah bawah
          echo "IMAGE_URI=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV

      - name: Generate Dockerrun.aws.json
        run: |
          # Membuat file konfigurasi EB secara otomatis menunjuk ke Image ECR yang baru
          echo '{
            "AWSEBDockerrunVersion": "1",
            "Image": {
              "Name": "'"$IMAGE_URI"'",
              "Update": "true"
            },
            "Ports": [
              {
                "ContainerPort": 5000,
                "HostPort": 80
              }
            ]
          }' > Dockerrun.aws.json
          
          # Cek isinya (untuk debug di logs)
          cat Dockerrun.aws.json

      - name: Zip Deployment Package
        run: |
          # Kita cuma butuh kirim file JSON ini, bukan source code Python-nya
          zip deploy-package.zip Dockerrun.aws.json

      - name: Upload ZIP to S3
        run: |
          aws s3 cp deploy-package.zip s3://${{ secrets.S3_BUCKET_NAME }}/deploy-package-${{ github.sha }}.zip

      - name: Deploy to Elastic Beanstalk
        run: |
          # Buat App Version Baru
          aws elasticbeanstalk create-application-version \
            --application-name ${{ secrets.EB_APP_NAME }} \
            --version-label ${{ github.sha }} \
            --source-bundle S3Bucket=${{ secrets.S3_BUCKET_NAME }},S3Key=deploy-package-${{ github.sha }}.zip

          # Update Environment ke Versi Baru
          aws elasticbeanstalk update-environment \
            --environment-name ${{ secrets.EB_ENV_NAME }} \
            --version-label ${{ github.sha }}